version: '3.1'

services:
  db:
    build: ./db
    container_name: postgres
    restart: always
    ports:
      - "5436:5432"

  nats:
    image: nats:2.8-alpine
    container_name: nats
    command: "-js -sd /data"
    volumes:
      - nats:/data
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  nats: